# Generated by Django 3.2.4 on 2021-06-10 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='poll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api.poll'),
        ),
        migrations.AlterField(
            model_name='result',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choice_results', to='api.choice'),
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together={('choice', 'poll', 'ip_address')},
        ),
    ]
